sudo: required
services:
  - docker

before_install:
  - docker build -t onikitin03/docker-react -f Dockerfile.dev .

script:
  - docker run -it onikitin03/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env-1"
  bucket-name: "elasticbeanstalk-us-east-2-584150016303"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"